---
- name: Get ssh key
  command: cat ~/.ssh/id_rsa.pub
  register: gce_ssh_pub_key
  changed_when: "gce_ssh_pub_key.rc != 0"

- name: Create network
  gce_net:
    name: privatenet
    state: present
    ipv4_range: "10.240.16.0/24"
    service_account_email: "{{ gce.service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ gce.project_id }}"

- name: Allow icmp
  gce_net:
    name: privatenet
    fwname: "{{ gce.name }}-icmp"
    allowed: "icmp"
    state: present
    src_range: "0.0.0.0/0"
    service_account_email: "{{ gce.service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ gce.project_id }}"

- name: Open tcp/udp ports
  gce_net:
    name: privatenet
    fwname: "{{ gce.name }}-ports"
    allowed: "tcp:22,{{ shadowsocks.server_port }};udp:8540"
    state: present
    src_range: "0.0.0.0/0"
    service_account_email: "{{ gce.service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ gce.project_id }}"

- name: Create instance
  gce:
    instance_names: "{{ gce.name }}"
    network: privatenet
    zone: "{{ gce.region }}"
    machine_type: "{{ gce.machine_type }}"
    image: "{{ gce.image }}"
    state: present
    service_account_email: "{{ gce.service_account_email }}"
    credentials_file: "{{ credentials_file }}"
    project_id: "{{ gce.project_id }}"
    metadata: '{"sshKeys":"{{ gce.user }}:{{ gce_ssh_pub_key.stdout }}"}'
  register: gce_server

- name: Wait until the server has finished start
  wait_for:
    host: "{{ gce_server.instance_data[0].public_ip }}"
    port: 22
    search_regex: OpenSSH
    timeout: 600

- name: Create host group
  add_host:
    name: "{{ gce_server.instance_data[0].public_ip }}"
    groups: gce
    ansible_user: "{{ gce.user }}"
    ansible_become: yes
